<?xml version="1.0" encoding="utf-8"?><Database Name="QLGame" Class="QLGAMEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-4SS0M3U\SQLEXPRESS01;Initial Catalog=QLGame;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLGameConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="MaGame" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGame" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Game_ThuVien" Member="ThuViens" ThisKey="MaGame" OtherKey="MaGame" Type="ThuVien" />
      <Association Name="NhaXuatBan_Game" Member="NhaXuatBan" ThisKey="MaNXB" OtherKey="MaNXB" Type="NhaXuatBan" IsForeignKey="true" />
      <Association Name="TheLoai_Game" Member="TheLoai" ThisKey="MaLoai" OtherKey="MaLoai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuVien" Member="ThuViens">
    <Type Name="ThuVien">
      <Column Name="MaTV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTK" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaGame" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayMua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Game_ThuVien" Member="Game" ThisKey="MaGame" OtherKey="MaGame" Type="Game" IsForeignKey="true" />
      <Association Name="TaiKhoan_ThuVien" Member="TaiKhoan" ThisKey="MaTK" OtherKey="MaTK" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaXuatBan" Member="NhaXuatBans">
    <Type Name="NhaXuatBan">
      <Column Name="MaNXB" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhaXuatBan_Game" Member="Games" ThisKey="MaNXB" OtherKey="MaNXB" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaTK" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoDu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_ThuVien" Member="ThuViens" ThisKey="MaTK" OtherKey="MaTK" Type="ThuVien" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TheLoai_Game" Member="Games" ThisKey="MaLoai" OtherKey="MaLoai" Type="Game" />
    </Type>
  </Table>
</Database>